INSERT INTO news_articles (external_id, title, description, source_name, url, published_at, query_tag, plant_codes, owner_names, states, fuel_types, topics, sentiment_label, event_type, impact_tags, fti_relevance_tags, importance, entity_company_names, llm_classified_at)
VALUES
('test-001','Vogtle Unit 4 reaches full commercial operation ahead of schedule','Georgia Power''s Vogtle Unit 4 nuclear plant has achieved full commercial operation, delivering 1,100 MW to the Georgia grid.','Power Magazine','https://example.com/vogtle-unit4-commercial','2026-02-28T14:00:00Z','plant:649',ARRAY['649'],ARRAY['Georgia Power'],ARRAY['GA'],ARRAY['Nuclear'],ARRAY['regulatory','construction'],'positive','commissioning',ARRAY['capacity_addition'],ARRAY['transactions','market_strategy'],'high',ARRAY['Georgia Power','Southern Company'],'2026-02-28T15:00:00Z'),
('test-002','Vogtle nuclear plant faces FERC scrutiny over transmission interconnection costs','Federal regulators are investigating cost allocation disputes at Plant Vogtle following complaints from neighboring utilities.','S&P Global','https://example.com/vogtle-ferc-transmission','2026-02-25T10:00:00Z','plant:649',ARRAY['649'],ARRAY['Georgia Power'],ARRAY['GA'],ARRAY['Nuclear'],ARRAY['regulatory'],'negative','regulatory_action',ARRAY['regulatory_risk'],ARRAY['disputes','restructuring'],'high',ARRAY['Georgia Power','FERC'],'2026-02-25T11:00:00Z'),
('test-003','Palo Verde nuclear plant extends operating license through 2047','The NRC approved a 20-year license extension for Palo Verde Generating Station, the largest nuclear plant in the US at 3,942 MW.','Reuters','https://example.com/palo-verde-license','2026-02-20T09:00:00Z','plant:6008',ARRAY['6008'],ARRAY['Arizona Public Service'],ARRAY['AZ'],ARRAY['Nuclear'],ARRAY['regulatory'],'positive','regulatory_action',ARRAY['regulatory_approval'],ARRAY['transactions','market_strategy'],'high',ARRAY['Arizona Public Service','NRC'],'2026-02-20T10:00:00Z'),
('test-004','Browns Ferry Unit 2 forced outage following equipment failure','Tennessee Valley Authority reported an unplanned shutdown of Browns Ferry Unit 2 after a feedwater pump failure. The 1,065 MW unit is expected offline for two weeks.','Platts','https://example.com/browns-ferry-outage','2026-02-22T16:00:00Z','plant:46',ARRAY['46'],ARRAY['Tennessee Valley Authority'],ARRAY['AL'],ARRAY['Nuclear'],ARRAY['outage'],'negative','unplanned_outage',ARRAY['generation_loss'],ARRAY['restructuring','disputes'],'high',ARRAY['Tennessee Valley Authority'],'2026-02-22T17:00:00Z'),
('test-005','Palo Verde considers hydrogen co-production pilot to boost revenue','Arizona Public Service is evaluating a clean hydrogen facility co-located with Palo Verde under a DOE grant to provide additional revenue streams.','Bloomberg NEF','https://example.com/palo-verde-hydrogen','2026-02-18T12:00:00Z','plant:6008',ARRAY['6008'],ARRAY['Arizona Public Service'],ARRAY['AZ'],ARRAY['Nuclear'],ARRAY['financial','construction'],'positive','corporate_strategy',ARRAY['new_revenue'],ARRAY['transactions','market_strategy'],'medium',ARRAY['Arizona Public Service','DOE'],'2026-02-18T13:00:00Z'),
('test-006','Georgia Power seeks rate increase to recover Vogtle construction overruns','Southern Company subsidiary Georgia Power filed for a 12% rate hike with the Georgia PSC to recover $4.7 billion in Vogtle cost overruns, drawing strong opposition from industrial customers.','Wall Street Journal','https://example.com/vogtle-rate-case','2026-02-15T08:00:00Z','plant:649',ARRAY['649'],ARRAY['Georgia Power'],ARRAY['GA'],ARRAY['Nuclear'],ARRAY['regulatory','financial'],'negative','rate_case',ARRAY['cost_recovery','regulatory_risk'],ARRAY['disputes','restructuring'],'high',ARRAY['Georgia Power','Southern Company','Georgia PSC'],'2026-02-15T09:00:00Z')
ON CONFLICT (external_id) DO NOTHING;
