-- Add portfolio_synopsis to entity stats tables
-- Stores per-asset breakdown generated by analyze functions (no dollar amounts)
ALTER TABLE lender_stats     ADD COLUMN IF NOT EXISTS portfolio_synopsis text;
ALTER TABLE tax_equity_stats ADD COLUMN IF NOT EXISTS portfolio_synopsis text;
ALTER TABLE company_stats    ADD COLUMN IF NOT EXISTS portfolio_synopsis text;
